apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrations-db
  namespace: integrations
  labels:
    project: integrations
    service: integrations
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      project: integrations
      service: integrations
      type: db
  template:
    metadata:
      labels:
        project: integrations
        service: integrations
        type: db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: integrations-db
          image: postgres:16.3-alpine
          resources:
            requests:
              memory: '500Mi'
              cpu: '0.5'
            limits:
              memory: '2Gi'
              cpu: '1'
              ephemeral-storage: 5Gi
          envFrom:
            - secretRef:
                name: integrations
          volumeMounts:
            - name: persistent-volume
              mountPath: /var/lib/postgresql/data
              subPath: database
          ports:
            - containerPort: 5432
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: integrations
