apiVersion: v1
kind: Service
metadata:
  name: integrations-db
  namespace: integrations
spec:
  selector:
    project: integrations
    service: integrations
    type: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
